### ISSUE TITLE
Build a web front-end for the Pattern Directory

### ISSUE THREAD

**Issue by tellyworth** [WordPress/pattern-directory#11]
The Pattern Directory will need a web-based front end for searching and browsing patterns, broadly similar to the plugin directory or theme directory sub-sites on WordPress.org.

Tentative assumptions:
- [x] This can probably be built as a WordPress theme, in a similar manner to the plugin directory. (#25)
- [x] The design and general structure can initially be based on the plugin directory.
- [x] Some kind of previews or screenshots of patterns will be important.
- [ ] Other metadata should be searchable and displayed, such as descriptions, tags, and locale. (partially covered by #28)
- [x] It should be possible for users to rate or vote for patterns.
- [x] Some kind of category structure should be considered.
- [x] Users should be able to easily find their own patterns. #16 
- [x] It should be easy for users to take a pattern from the web front-end and use it in a post on their own site.
- [x] There should be a mechanism for users to help translate a pattern.

This is an umbrella task.

**Comment by ryelle** [comment]
Closing this issue - items are either done, or being tracked in other issues.
