### ISSUE TITLE
Create "My Submitted Patterns" page

### ISSUE THREAD

**Issue by MichaelArestad** [WordPress/pattern-directory#16]
There should a page a user can see their submitted patterns and the status of those patterns.

* What are the various statuses of the patterns (submitted, reviewed, rejected)?
* How should a user get to this page? Is there something similar for plugins?

**Comment by iandunn** [comment]
> rejected

The Community Team uses `declined` as a softer word in those situations, and I think it's worked well there.

**Comment by iandunn** [comment]
>  Is there something similar for plugins?

[The Add Your Plugin page](https://wordpress.org/plugins/developers/add/)  will show everyone how many are in the review queue, but I think the accepted/rejected notes are sent via email.

Is that right, @Ipstenu ?

**Comment by iandunn** [comment]
> How should a user get to this page?

I think the only way to see all of your plugins is on profiles.w.org. I think it'd be good to add patterns there, for consistency. 

I don't think that's easy to find, though. I like how [the 5ftF design has a `My Pledges` link in the navbar](https://wordpress.org/five-for-the-future/for-organizations/). That could link to the patterns on the profile, so we don't have to create duplicate pages.

**Comment by Ipstenu** [comment]
Rejections are kinda saved -- everyone who has a rejected plugin, has it listed on the 'author' card:

![Screen Shot 2020-11-11 at  11 Nov - 12 12 11 PM](https://user-images.githubusercontent.com/807903/98859520-2a739e00-2417-11eb-9d74-501f84fd1b50.jpg)

And everyone gets an email (except for 'it's been 6 months...'). As you can see, we don't track 'why' something was rejected. Most of the time we use it for "We've rejected Bob for the same plugin 3 times. Check the emails and see if he's just not getting something or if we have a bigger issue."

In general, rejections are:

* Submitter took 6 months and never finished the review
* Plugin is not acceptable
* Specific issue with submitter

**Comment by tellyworth** [comment]
@MichaelArestad raised the interesting idea that people might like to use this as a repository for their own patterns. For example a designer or integrator might keep a library of patterns for easy access on their client sites.

We won't have any way to authenticate users from an external editor, which means they can't be completely private. But I wonder if this hints at a more nuanced set of statuses than for the plugin/theme directories. Something like:

* I create/remix a pattern and save it.
* It's now accessible to me (as author) on the front end of the directory, but not visible there to others or logged-out users.
* From the Gutenberg editor on my site, I can search for my pattern with some kind of explicit prefix, like "user:tellyworth green button"
* If I want to publish it to the world, I can go back to the directory and "submit".
* If it's reviewed and accepted, it becomes visible on the directory front end and searchable from the pattern tab in the editor as "green button".
* If it's declined or still pending review it stays in the "private" state.

That suggests something slightly more complex than 3 status values.

**Comment by MichaelArestad** [comment]
@tellyworth Exactly. I don't think we need to start with that feature as a priority, but down the road, it could be a nice enhancement.

**Comment by carolinan** [comment]
Please consider allowing contributors to remove and transfer their patterns as well.
I don't know how the plugin team handles it but for themes this process is manual.

**Comment by ryelle** [comment]
Design for "My Patterns"

![Pending Review](https://user-images.githubusercontent.com/541093/113023648-d95d1000-9153-11eb-8cff-483bd62cc237.png)
![Successfuly Published](https://user-images.githubusercontent.com/541093/113023644-d95d1000-9153-11eb-86f1-6395576ae082.png)

There's also more information, including an edit button, in the header of owned pattern details. The note about transferring ownership & removal is a good point, @shaunandrews where do you think that could fit in?

![Pattern Detail - Owned - Pending](https://user-images.githubusercontent.com/541093/113023361-871bef00-9153-11eb-91bf-d35524fa400a.png)

**Comment by shaunandrews** [comment]
Instead of a single "Edit" button, perhaps we show a menu with multiple options including transferring ownership and deleting:

<img width="765" alt="image" src="https://user-images.githubusercontent.com/191598/113446922-d9b11180-93c6-11eb-96e9-ebc4cb13c043.png">

We can also expose this menu in the grid view of patterns:

<img width="330" alt="image" src="https://user-images.githubusercontent.com/191598/113448271-82f90700-93c9-11eb-8545-8369b32b42eb.png">

**Comment by ryelle** [comment]
To do here (create individual issues before tackling):

- [ ] Create the My Patterns page
- [ ] Update the grid component to separate it from the main query, so we can have multiple grids on one page
- [ ] Show the user's patterns in a grid (if any)
    - [ ] Allow filtering by status
    - [ ] Patterns should have a status label #103
- [ ] Show the user's favorites in a grid (if any)

![My Patterns](https://user-images.githubusercontent.com/541093/117727985-cd368a80-b1b6-11eb-9a7e-642d3c941558.png)

In the design, there is one pagination, but two queries — should we show all owned patterns, and paginate favorites? or somehow paginate both? Or maybe we should create two pages after all, "my patterns" and "my favorites"?

What does the "featured" dropdown do in the favorites grid?

**Comment by shaunandrews** [comment]
> there is one pagination, but two queries — should we show all owned patterns, and paginate favorites? or somehow paginate both? Or maybe we should create two pages after all, "my patterns" and "my favorites"?

My intention with the design was that each group would be it's own query, each with their own pagination. This is obviously not great, especially if we consider someone with more than a handful of both owned patterns and favorites. I think we should just split these up after all:

<img width="1770" alt="image" src="https://user-images.githubusercontent.com/191598/117884197-54006b80-b27a-11eb-9021-6fb512e9f43a.png">

"My patterns" gets a button to create a new pattern, a filter for status, and a sort menu. "Favorites" has a category filter (maybe only show the categories that exist within the collection) and a sort menu.

> What does the "featured" dropdown do in the favorites grid?

That's the "sort by" menu, which allows you to control the order of the items in the grid. In the context of "My patterns" and "Favorites" I think the options should be date (last updated), views, and favorites. The featured option doesn't really make sense on these screens.

**Comment by ryelle** [comment]
An issue was created for the favorites page - #239. The remaining task for this issue is the management dropdown.
