### ISSUE TITLE
Translation mechanism for submitted patterns

### ISSUE THREAD

**Issue by tellyworth** [WordPress/pattern-directory#224]
Here's a proposal for handling translation of third-party user-submitted patterns in the directory.

Some of the pieces of the core pattern translation mechanism would be used, except GlotPress would not be involved at all.

When creating and submitting a new pattern, the user will choose a locale for their pattern. That will be stored in a taxonomy as described in #223.

Translating a pattern to a new language will be essentially the same as creating a copy of the original, editing the text as needed, and setting a different locale for the new pattern.

Translated patterns will have the `post_parent` field set to record the relationship to its original source.

In other words, translating a pattern is basically the same as remixing. This means that translating can incorporate non-text changes as needed. For example, images could be changed, and designs could be changed to suit right-to-left languages.

The main pieces needed for this are:

* [x] Create a locale ~taxonomy~ storage mechanism (#229)
* [x] Add UI for setting the locale when creating a pattern (#229)
* [x] #244 v1 w/ WP_Query
* [x] #244 v2 w/ ElasticSearch
* [x] Cron job that creates/updates patterns from GlotPress
- [x] #391
- [ ] #392

~Add a Translate This button, that: (#17)~
  * Opens a new creator window with a copy of the pattern
  * with the `post_parent` set to the original pattern post_id
  * and a different locale selected

**Comment by coreymckrill** [comment]
I converted this to a tracking issue so we can connect and add other issues for specific parts of this.

**Comment by ryelle** [comment]
Pulling this out of initial launch, since the remaining tasks are for post-launch.

>  Cron job that creates/updates patterns from GlotPress

This one's done, right?

**Comment by iandunn** [comment]
Yeah, #250 did it. I marked it as done, thanks!

**Comment by ryelle** [comment]
Once pattern creation is built, how should submissions work across languages? I'm assuming the creator will be available on all Rosetta sites, so a designer could create a Japanese pattern on ja.w.org/patterns, with no English original. Then again, someone could also create an English pattern on ja.w.org/patterns, so maybe we'll need a dropdown with the current site's locale as default.

How do we see the GlotPress translation flow working with future submitted patterns? Was the GlotPress flow just for this initial set of patterns, or is that the preference of translators?

**Comment by varlese** [comment]
We had a small discussion about the proposed options for translation mechanisms [over on Make/Polyglots](https://make.wordpress.org/polyglots/2021/09/19/how-to-handle-block-pattern-translations/). From the feedback:
- Everyone who commented preferred keeping translations in GlotPress (using the existing translation mechanism) over creating a forked pattern. 
- The main concern around moving translations from GlotPress is that translated versions of block patterns wouldn't need to be reviewed by locale managers and translation editors - which could mean a loss of translation consistency, or even poor translation quality (i.e. unreviewed machine translation).
- As a long-term solution to having the GlotPress project grow infinitely, there were two comments that suggested some [form of "default" text or reusable text ](https://make.wordpress.org/polyglots/2021/09/19/how-to-handle-block-pattern-translations/#comment-292898)- in other words, find a way to encourage users submitting block patterns to use pre-defined demo text so there are fewer strings to translate in the future. 

I'm hoping to see some more comments as others come across the post, just for more voices! However, the general summary is that using GlotPress for translating user-generated block patterns is strongly preferred, particularly to maintain a consistent translation quality and user experience.

**Comment by ryelle** [comment]
To continue with the current GlotPress solution, we just need to remove [the restriction on which patterns get imported](https://github.com/WordPress/pattern-directory/blob/eab19454d86b9714dd4dd84d067dd78a2bb164a8/public_html/wp-content/plugins/pattern-translations/includes/pattern.php#L132-L136). Then, any new pattern will be automatically imported.

A default text library would be neat, I'm not totally sure how that could work but we can think about that for later. It would probably help with quality of patterns in general, so they're not all Lorem Ipsum 🙂

**Comment by ryelle** [comment]
Created #391 & #392 to track those two tasks, since only one is needed for launch. Closing this tracking issue.
