### ISSUE TITLE
Pattern moderation

### ISSUE THREAD

**Issue by coreymckrill** [WordPress/pattern-directory#55]
As mentioned in #8, workflows and tools are needed to be able to moderate patterns that have been submitted to the directory, whether that moderation happens before or after the pattern is published and available.

Since patterns are a custom post type, the main screen for moderating patterns will probably be the patterns list table screen.

Each of these can probably have their own issue:

* [x] Custom statuses for different parts of a pattern's life cycle (#56, #107)
* [x] A field for adding private notes, possibly connected to status changes (#105)
* [x] A logging mechanism to record who changed the status, and when (#57)
* [x] Email notifications to a pattern author when a status changes (#58)
* [x] A way to collect submissions of flags/reports about a pattern on the front end (#61, #80)
* [x] Columns for the list table, e.g. status, author, reports, ratings, etc. (#63)
* [x] Filter views for the list table, e.g. to show only patterns with a particular status (#63)
