### ISSUE TITLE
Build the Pattern Directory back-end

### ISSUE THREAD

**Issue by tellyworth** [WordPress/pattern-directory#8]
The back-end for the block pattern directory should be broadly modeled on the plugin directory, and can probably import some of the code.

Tentative assumptions:
- [x] Patterns should be stored in CPTs (#6).
- [x] Each pattern would have metadata such as author, title, description, tags, language, screenshots. Partially done in #6.
- [x] #279
- [x] There should be an API endpoint for searching and fetching patterns. (#6)
- [ ] Pattern searching should use ElasticSearch in a similar fashion to the plugin directory (#28).
- [ ] Some kind of curation or moderation will needed.
- [x] Some kind of user-submitted ratings or voting will be needed.
- [ ] Some kind of popularity stats will be needed. (#24)

This is an umbrella task, separate issues should be created for the various parts.

**Comment by iandunn** [comment]
I took the liberty of editing the issue to make it a checklist, and reference other tickets. Feel free to revert if you don't think that's helpful.

**Comment by ryelle** [comment]
The only item on this list that doesn't also have an issue is the "pattern moderation" item. Since we're not accepting submissions for initial launch, I don't think this needs to apply (and also might be captured under #22). I'm going to close this tracking issue, the other tasks can be tracked in their respective issues.
